version: '3.8'

services:
  android-builder:
    build: .
    container_name: zlecenia-pro-builder
    volumes:
      - .:/app
    environment:
      - BUILDOZER_WARN_ON_ROOT=0
    working_dir: /app
    stdin_open: true
    tty: true
    command: |
      bash -c "
        echo '🚀 Rozpoczynam budowanie APK (bez ostrzeżeń root)...'
        echo 'y' | buildozer android debug || buildozer android debug
        echo '✅ Budowanie zakończone!'
        ls -la bin/
      "